export default {
  login: 'Atharv-02',
  id: 95168968,
  node_id: 'U_kgDOBawpyA',
  avatar_url: 'https://avatars.githubusercontent.com/u/95168968?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Atharv-02',
  html_url: 'https://github.com/Atharv-02',
  followers_url: 'https://api.github.com/users/Atharv-02/followers',
  following_url:
    'https://api.github.com/users/Atharv-02/following{/other_user}',
  gists_url: 'https://api.github.com/users/Atharv-02/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Atharv-02/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Atharv-02/subscriptions',
  organizations_url: 'https://api.github.com/users/Atharv-02/orgs',
  repos_url: 'https://api.github.com/users/Atharv-02/repos',
  events_url: 'https://api.github.com/users/Atharv-02/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Atharv-02/received_events',
  type: 'User',
  site_admin: false,
  name: 'Atharv Gulati',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 20,
  public_gists: 0,
  followers: 1,
  following: 0,
  created_at: '2021-11-28T11:01:15Z',
  updated_at: '2022-11-30T16:54:45Z',
};
